-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 16:01:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_projetointegrado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_projetointegrado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projetointegrado` DEFAULT CHARACTER SET utf8 ;
USE `db_projetointegrado` ;

-- -----------------------------------------------------
-- Table `db_projetointegrado`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projetointegrado`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projetointegrado`.`tb_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projetointegrado`.`tb_temas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `emalta` TINYINT NULL,
  `iniciativas` TINYINT NULL,
  `eventos` TINYINT NULL,
  `educacao` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projetointegrado`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projetointegrado`.`tb_postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `horario` VARCHAR(255) NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `anexo` VARCHAR(255) NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(280) NULL,
  `tb_usuario_id` BIGINT NULL,
  `tb_temas_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagem_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_temas1_idx` (`tb_temas_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `db_projetointegrado`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_temas1`
    FOREIGN KEY (`tb_temas_id`)
    REFERENCES `db_projetointegrado`.`tb_temas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
